---
version: "4"
services:
  base:
    build:
      context: .
      dockerfile: containers/Containerfile
      network: host
      args:
        - CONTEXT_ROOT=containers
      target: base
      secrets:
        - pip.conf
    image: packtly-builder-base:latest

  devcontainer:
    build:
      context: .
      dockerfile: containers/Containerfile
      network: host
      args:
        - CONTEXT_ROOT=containers
      target: build
      secrets:
        - pip.conf
    image: packtly-builder-devcontainer:latest
    volumes:
      - ..:/workspace:Z
      - ../Keys/gpg:/opt/keys/gpg:Z
    network_mode: host
    secrets:
      - source: pip.conf
        target: /etc/pip.conf
    cap_add:
      - NET_RAW
    entrypoint: ["dumb-init", "--", "sleep", "infinity"]

  builder:
    build:
      context: .
      dockerfile: containers/Containerfile
      network: host
      args:
        - CONTEXT_ROOT=containers
      target: build
      secrets:
        - pip.conf
    image: packtly-builder-builder:latest
    volumes:
      - ..:/workspace:Z
    network_mode: host
    secrets:
      - source: pip.conf
        target: /etc/pip.conf
    working_dir: /workspace/packtly-builder/tooling
    environment:
      APTLYHOST: "localhost"
    entrypoint: ["just"]

  runtime:
    build:
      context: .
      dockerfile: containers/Containerfile
      network: host
      args:
        - CONTEXT_ROOT=containers
      target: image
      secrets:
        - pip.conf
    image: packtly-builder:latest

secrets:
  pip.conf:
    file: ${HOME}/.pip/pip.conf
