---
version: "4"
services:
  base:
    build:
      context: .
      dockerfile: containers/Containerfile
      network: host
      args:
        - CONTEXT_ROOT=containers
      target: base
      secrets:
        - pip.conf
    platform: ${PLATFORM:-linux/amd64}
    image: packtly-builder-base:latest

  builder:
    build:
      context: .
      dockerfile: containers/Containerfile
      network: host
      args:
        - CONTEXT_ROOT=containers
      target: build
      secrets:
        - pip.conf
    platform: ${PLATFORM:-linux/amd64}
    image: packtly-builder-builder:latest
    volumes:
      - ..:/workspace:Z
    network_mode: host
    secrets:
      - source: pip.conf
        target: /etc/pip.conf
    working_dir: /workspace/packtly-builder/tooling
    environment:
      APTLYHOST: "localhost"
    entrypoint: ["just"]

  runtime:
    build:
      context: .
      dockerfile: containers/Containerfile
      network: host
      args:
        - CONTEXT_ROOT=containers
      target: image
      secrets:
        - pip.conf
    platform: ${PLATFORM:-linux/amd64}
    image: packtly-builder:latest

secrets:
  pip.conf:
    file: ${HOME}/.config/pip/pip.conf
