name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-24.04

    outputs:
      release_version: ${{ steps.context.outputs.release_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Get release version
        id: context
        uses: ./.github/actions/get-version

  builder-image:
    needs: version
    uses: ./.github/workflows/_build-builder-image.yml
    with:
      release_version: ${{ needs.version.outputs.release_version }}
    secrets: inherit

  tooling:
    needs:
      - version
      - builder-image
    uses: ./.github/workflows/_tooling.yml
    with:
      release_version: ${{ needs.version.outputs.release_version }}
    secrets: inherit
    permissions:
      checks: write
      pull-requests: write
      contents: read
      actions: read

  runtime-image:
    needs:
      - version
      - tooling
    uses: ./.github/workflows/_build-runtime-image.yml
    with:
      release_version: ${{ needs.version.outputs.release_version }}
    secrets: inherit

  runtime-manifest:
    needs:
      - version
      - runtime-image
    uses: ./.github/workflows/_runtime-manifest.yml
    with:
      release_version: ${{ needs.version.outputs.release_version }}
    secrets: inherit
    permissions:
      packages: write

  robot-tests:
    needs:
      - runtime-manifest
    uses: ./.github/workflows/_robot-tests.yml
    with:
      release_version: ${{ needs.version.outputs.release_version }}
    secrets: inherit
    permissions:
      checks: write
      pull-requests: write
